apiVersion: v1
kind: Service
metadata:
  name: redis
  # namespace: my-redis  # Specify the namespace
spec:
  type: NodePort  # Change to NodePort for external access
  ports:
  - port: 6379
    nodePort: 30000  # You can specify a port or let Kubernetes assign one
  selector:
    app: redis