apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  # namespace: my-redis  # Specify the namespace
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    appendonly yes


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  # namespace: my-redis  # Specify the namespace
spec:
  serviceName: "redis"
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        ports:
        - containerPort: 6379
      volumes:
      - name: redis-config
        configMap:
          name: redis-config


apiVersion: v1
kind: Service
metadata:
  name: redis
  # namespace: my-redis  # Specify the namespace
spec:
  type: NodePort  # Change to NodePort for external access
  ports:
  - port: 6379
    nodePort: 30000  # You can specify a port or let Kubernetes assign one
  selector:
    app: redis