apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-server
  labels:
    app: whiteboard-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whiteboard-server
  template:
    metadata:
      labels:
        app: whiteboard-server
    spec:
      containers:
        - name: whiteboard-server
          image: nickifeajika/whiteboard-server
          env:
          - name: REDIS_PASSWORD
            value: a-weak-password
          - name: REDIS_MASTER_PASSWORD
            value: a-weak-password
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
          ports:
            - containerPort: 5000
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoreDuringExecution:
      #     - labelSelector:
      #       matchExpressions:
      #       - key: app
      #         operator: In
      #         values:
      #         - whiteboard-server

---
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-server
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    any-name: whiteboard-server