apiVersion: v1
kind: Service
metadata:
  name: whiteboard-loadbalancer
spec:
  selector:
    app: whiteboard-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer